# Generated by Django 5.1 on 2024-08-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default=None, max_length=20)),
                ('Last_name', models.CharField(default=None, max_length=20)),
                ('Age', models.IntegerField(default=None)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('Branch', models.CharField(max_length=30)),
            ],
        ),
    ]
