# Generated by Django 5.1 on 2024-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_applicant_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Last_name',
            field=models.CharField(max_length=20),
        ),
    ]
